/**
 * markdownSpec.ts — スライドMD記法の仕様書（Markdown文書）を組み立てる純関数。
 *
 * 想定される出力先:
 *   - `mdss-convert --print-spec`（外部スキル・ドキュメントへ配布する仕様書）
 *
 * SSOT方針:
 *   - type別の制約・1行説明は schema の `.meta()`（describe.ts）から生成する。
 *     ここに制約数値を手で書き足さないこと。
 *   - 各typeの「実際の記法サンプル」はここに再掲しない。sample.md（`--sample-md`）が実例の正であり、
 *     再掲すると slideTemplates.ts / sample.md と三重管理になるため。
 *     本ファイル＝規約、sample.md＝実例、という役割分担にしている。
 *   - デッキ全体のルール（DECK_LEVEL_RULES）は特定のtype schemaに属さない（deckLint.ts の責務）ため、
 *     ここを正とし、app 側の helpContent.ts は import して再利用する。
 */
import { buildConstraintRules, buildTypeReferenceTable } from '../schema/describe';

/** スライドMD記法のバージョン表記（元スキル v0.7 系 ＋ Studio拡張）。 */
export const SLIDE_MD_SPEC_VERSION = 'v0.7 + Studio拡張 v0.2.3';

/**
 * デッキ全体に関わるルール（特定のtype schemaに属さない＝deckLint.ts の責務）。
 * 文言は HelpModal のE2E（e2e/help.spec.ts）がアサートしているため、変更時は要確認。
 */
export const DECK_LEVEL_RULES: string[] = [
  '最終スライドは sources（出典）を推奨',
  '先頭スライドは title を推奨',
  'グラフ・図解・画像は同一スライドに共存させない',
  '枚数の厳密な上限はなし。AIへ依頼する際の目安は8〜16枚',
];

/** 最小構成のデッキ例（title → points → sources）。 */
export const MINIMAL_DECK_EXAMPLE = [
  '---',
  'title: サンプル',
  'palette: ocean',
  '---',
  '<!-- slide: title -->',
  '# サンプルタイトル',
  'subtitle: サブタイトル',
  '---',
  '<!-- slide: points -->',
  '## 要点',
  '- **要点1**：説明',
  '- **要点2**：説明',
  '---',
  '<!-- slide: sources -->',
  '## 出典',
  '- [出典1](https://example.com) — 補足',
  '',
].join('\n');

/** YAML検証を持たない（記法が固定の）type の書き方。 */
const PLAIN_TYPE_NOTATION: string[] = [
  '- `title`: `# 見出し`（必須）＋ `subtitle:` ＋ `badges: [tag1, tag2]`',
  '- `points`: `## 見出し` ＋ `- **リード**：説明` の箇条書き（ネストは2段まで）。末尾の `> 行` は補足ノート',
  '- `summary`: `points` と同じ記法で `1.` の番号付きリストを使う（番号バッジ付きで描画）',
  '- `table`: `## 見出し` ＋ 標準のMarkdownテーブル（5列以下を推奨）',
  '- `figure`: `## 見出し` ＋ `![alt](画像URL)` ＋ `source: [出典名](URL)`（`source:` は必須）',
  '- `sources`: `- [タイトル](URL) — 補足` のリンクリスト（最終スライドに置く）',
];

/** `layout:` バリアントの一覧（parser の LAYOUTS と描画側の実装に対応）。 */
const LAYOUT_TABLE: string[] = [
  '| type | `layout:` | 効果 |',
  '|---|---|---|',
  '| `title` | `title-xl` | 見出しを拡大する |',
  '| `title` | `split-image` | 右半分に画像を置く（`image:` にURL）。外部画像はPNG/ZIP出力時にCORSで失敗しうる |',
  '| `points` / `summary` | `two-col` | 本文を2カラム化する |',
  '| `summary` / `table` | `compact` | 余白を詰めて高密度に描画する |',
  '| `chart-bar` / `chart-line` | `side-list` | グラフの横に前提条件パネルを併記する |',
];

export interface MarkdownSpecOptions {
  /** 生成元の表示名（例: `mdss-convert v0.4.2`）。AUTO-GENERATED ヘッダに埋め込む */
  generator?: string;
}

/**
 * スライドMD記法の仕様書をMarkdown文字列として組み立てる。
 * 出力は決定論的（同じcore実装からは常に同じ文字列）。
 */
export function buildMarkdownSpec(opts: MarkdownSpecOptions = {}): string {
  const generator = opts.generator ?? 'mdss-convert --print-spec';
  const lines: string[] = [
    `<!-- AUTO-GENERATED by ${generator} — 手で編集しないこと（再生成で上書きされます） -->`,
    `# スライドMD 記法仕様（${SLIDE_MD_SPEC_VERSION}）`,
    '',
    'MD Slide Studio / mdss-convert が解釈するスライドMarkdown（スライドMD）の記法。',
    '**MDが唯一の情報源であり、HTMLはMDから毎回フル再生成する。**',
    'type別の制約は zod schema の meta を単一の情報源として自動生成している。',
    '',
    '全typeの実例は `mdss-convert --sample-md` で取得できる（本書＝規約 / sample.md＝実例）。',
    '',
    '---',
    '',
    '## 1. ファイル構造',
    '',
    '```markdown',
    '---',
    'title: デッキタイトル',
    'palette: ocean',
    '---',
    '<!-- slide: title -->',
    '（1枚目の内容）',
    '---',
    '<!-- slide: points -->',
    '（2枚目の内容）',
    '```',
    '',
    '- 先頭に YAML frontmatter、以降は**行全体が `---` の行**でスライドを区切る',
    '- frontmatter 内・コードフェンス内の `---` は区切りとみなさない',
    '- 各スライドの先頭行はスライドディレクティブ（HTMLコメント）',
    '',
    '### frontmatter キー',
    '',
    '| キー | 必須 | 値 |',
    '|---|---|---|',
    '| `title` | ✅ | 文字列。`<title>` とファイル名の元になる |',
    '| `palette` | — | `ocean` / `forest` / `sunset` / `plum` / `graphite`（既定 `ocean`。不正値は警告つきで `ocean`） |',
    '| `purpose` | — | `self-study` / `team-share` / `outreach`（作成目的。描画には影響しない） |',
    '',
    '## 2. スライドディレクティブ',
    '',
    '```',
    '<!-- slide: <type>[, fit][, layout: <variant>][, tone: dark] -->',
    '```',
    '',
    '| キー | 効果 |',
    '|---|---|',
    '| `fit` | 内容量が多いスライドを一覧表示時に自動縮小する |',
    '| `layout: <variant>` | type別のレイアウトバリアント（§4-3） |',
    '| `tone: dark` | そのスライドだけ地色を反転する（強調用。1デッキ2〜3枚まで） |',
    '',
    '未知のtype・未知の値はエラーにせず、警告つきでフォールバックする（落ちないパーサー）。',
    '',
    '## 3. 全typeで使える共通記法',
    '',
    '| 記法 | 位置 | 効果 |',
    '|---|---|---|',
    '| `badge: Step 1` | 本文の行頭 | 見出し左のピル（工程番号・ラベル） |',
    '| `lead: 補足文` | 本文の行頭 | 見出し直下のグレー1行 |',
    '| `point: 要点` | 本文の行頭 | スライド下部の強調帯（結論・注意点） |',
    '| `==テキスト==` | 本文中 | アクセント色のハイライト |',
    '| `**太字**` / `[label](url)` | 本文中 | インライン装飾。危険なURLスキームは無効化される |',
    '',
    '生の `<script>` / `<style>` は無視される（MD内に書かない）。',
    '',
    '## 4. type一覧（全16）',
    '',
    '### 4-1. 記法が固定のtype（YAML検証なし）',
    '',
    ...PLAIN_TYPE_NOTATION,
    '',
    '### 4-2. schemaで検証されるtype（この節は自動生成）',
    '',
    buildTypeReferenceTable(),
    '',
    '### 4-3. layout バリアント',
    '',
    ...LAYOUT_TABLE,
    '',
    '## 5. 制約',
    '',
    '### 5-1. デッキ全体',
    '',
    ...DECK_LEVEL_RULES.map((r) => `- ${r}`),
    '',
    '### 5-2. type別（この節は自動生成）',
    '',
    ...buildConstraintRules().map((r) => `- ${r}`),
    '',
    '## 6. 最小例',
    '',
    '```markdown',
    MINIMAL_DECK_EXAMPLE.trimEnd(),
    '```',
    '',
    '## 7. HTMLへの変換',
    '',
    '```bash',
    'mdss-convert deck.md -o deck.html           # スタンドアロンHTML',
    'mdss-convert deck.md --json-only            # 変換せず title/枚数/warnings/lint をJSONで確認',
    'mdss-convert deck.md -o deck.html --strict  # lint に error があれば出力せず exit 3',
    'mdss-convert --extract-md deck.html         # 生成HTMLから原稿MDを取り出す',
    '```',
    '',
    '生成HTMLには原稿MDが `DECK_MD` として同梱されるため、HTML→MDは推論なしで完全に復元できる。',
    '',
  ];
  return lines.join('\n');
}
