import { describe, expect, it } from 'vitest';
import { buildConstraintRules } from '../schema/describe';
import {
  buildMarkdownSpec,
  DECK_LEVEL_RULES,
  MINIMAL_DECK_EXAMPLE,
  SLIDE_MD_SPEC_VERSION,
} from './markdownSpec';
import { parseSlideMarkdown } from '../parser/slideMarkdown';

// スナップショットは取らない（節の追加のたびに壊れるため）。
// 「schemaの生成物が確実に流し込まれているか」と「必須の記法が抜けていないか」を見る。
const ALL_TYPES = [
  'title',
  'points',
  'summary',
  'table',
  'chart-bar',
  'chart-line',
  'chart-donut',
  'comparison-chart',
  'diagram-flow',
  'diagram-layer',
  'diagram-cycle',
  'diagram-timeline',
  'steps',
  'contrast',
  'figure',
  'feature-showcase',
  'sources',
] as const;

describe('buildMarkdownSpec', () => {
  it('全16 type が仕様書に登場する', () => {
    const spec = buildMarkdownSpec();
    for (const t of ALL_TYPES) {
      expect(spec, `type "${t}" が仕様書に含まれていません`).toContain(t);
    }
  });

  it('schema由来の制約（buildConstraintRules）が全件流し込まれる', () => {
    const spec = buildMarkdownSpec();
    for (const rule of buildConstraintRules()) {
      expect(spec).toContain(rule);
    }
  });

  it('デッキ全体ルールが全件流し込まれる', () => {
    const spec = buildMarkdownSpec();
    for (const rule of DECK_LEVEL_RULES) {
      expect(spec).toContain(rule);
    }
  });

  it('生成元とバージョンがヘッダに入る', () => {
    const spec = buildMarkdownSpec({ generator: 'mdss-convert v9.9.9' });
    expect(spec.startsWith('<!-- AUTO-GENERATED by mdss-convert v9.9.9')).toBe(true);
    expect(spec).toContain(SLIDE_MD_SPEC_VERSION);
  });

  it('決定論的（同じ入力から同じ文字列）', () => {
    expect(buildMarkdownSpec()).toBe(buildMarkdownSpec());
  });

  it('frontmatter・ディレクティブ・共通ヘッダキーの記述がある', () => {
    const spec = buildMarkdownSpec();
    expect(spec).toContain('frontmatter');
    expect(spec).toContain('<!-- slide: <type>[, fit][, layout: <variant>][, tone: dark] -->');
    expect(spec).toContain('badge:');
    expect(spec).toContain('lead:');
    expect(spec).toContain('point:');
  });
});

describe('MINIMAL_DECK_EXAMPLE', () => {
  it('警告0件でパースでき、title始まり sources終わりになる', () => {
    const deck = parseSlideMarkdown(MINIMAL_DECK_EXAMPLE);
    expect(deck.warnings).toEqual([]);
    expect(deck.slides.flatMap((s) => s.warnings)).toEqual([]);
    expect(deck.slides[0].type).toBe('title');
    expect(deck.slides[deck.slides.length - 1].type).toBe('sources');
  });
});
