/**
 * features.test.mjs — v0.4.2 で追加したスキル連携用オプションの統合テスト。
 *   --print-spec / --sample-md / --extract-md / --strict
 * 既存の smoke.test.mjs は変更せず、別ファイルとして追加している。
 *
 *   実行: node --test test/     （事前に build.mjs 済みであること）
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync, existsSync, rmSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const CLI = resolve(here, '..', 'dist', 'cli.mjs');
const SAMPLE = resolve(here, '..', '..', 'app', 'src', 'samples', 'sample.md');

function run(args, input) {
  return execFileSync('node', [CLI, ...args], {
    input,
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'ignore'],
  });
}

/** 失敗が期待されるケース用。{ status, stdout } を返す。 */
function runExpectFail(args, input) {
  try {
    const stdout = run(args, input);
    return { status: 0, stdout };
  } catch (e) {
    return { status: e.status, stdout: e.stdout ?? '' };
  }
}

const LINT_ERROR_MD = [
  '---',
  'title: lint error deck',
  '---',
  '<!-- slide: title -->',
  '# T',
  '---',
  '<!-- slide: contrast -->',
  '## example が無い contrast',
  '---',
  '<!-- slide: sources -->',
  '## 出典',
  '- [x](https://example.com)',
  '',
].join('\n');

test('--print-spec: 記法仕様書をMarkdownで出力する', () => {
  const spec = run(['--print-spec']);
  assert.match(spec, /^<!-- AUTO-GENERATED by mdss-convert v\d+\.\d+\.\d+/);
  assert.ok(spec.includes('# スライドMD 記法仕様'), '見出しがある');
  for (const t of ['title', 'points', 'steps', 'contrast', 'diagram-timeline', 'sources']) {
    assert.ok(spec.includes(t), `type ${t} が含まれる`);
  }
  assert.ok(spec.includes('最終スライドは sources（出典）を推奨'), 'デッキ全体ルールが入る');
});

test('--print-spec -o: ファイルへ書き出せる', () => {
  const dir = mkdtempSync(join(tmpdir(), 'mdss-'));
  const out = join(dir, 'spec.md');
  run(['--print-spec', '-o', out, '--quiet']);
  assert.ok(existsSync(out));
  assert.ok(readFileSync(out, 'utf-8').includes('スライドMD 記法仕様'));
  rmSync(dir, { recursive: true, force: true });
});

test('--sample-md: app の sample.md とバイト等価', () => {
  const out = run(['--sample-md']);
  assert.equal(out, readFileSync(SAMPLE, 'utf-8'));
  assert.ok(out.startsWith('---\ntitle:'), 'frontmatter付きで出力される');
});

test('--sample-md → 変換 → --extract-md で原稿MDが完全復元される', () => {
  const dir = mkdtempSync(join(tmpdir(), 'mdss-'));
  const html = join(dir, 'deck.html');
  const sample = run(['--sample-md']);
  run(['-', '-o', html, '--quiet'], sample);
  const extracted = run(['--extract-md', html]);
  assert.equal(extracted, sample, 'MD → HTML → MD が往復でバイト等価');
  rmSync(dir, { recursive: true, force: true });
});

test('--extract-md: stdin（-）からも読める', () => {
  const md = '---\ntitle: T\n---\n<!-- slide: title -->\n# Hello\n';
  const html = run(['-', '--quiet'], md);
  const extracted = run(['--extract-md', '-'], html);
  assert.equal(extracted, md);
});

test('--extract-md: 対象外のHTMLは exit 4', () => {
  const r = runExpectFail(['--extract-md', '-'], '<html><body>not mdss</body></html>');
  assert.equal(r.status, 4);
});

test('--strict: lint error があると exit 3 でHTMLを書き出さない', () => {
  const dir = mkdtempSync(join(tmpdir(), 'mdss-'));
  const out = join(dir, 'ng.html');
  const r = runExpectFail(['-', '-o', out, '--strict', '--quiet'], LINT_ERROR_MD);
  assert.equal(r.status, 3);
  assert.equal(existsSync(out), false, 'HTMLは書き出されない');
  rmSync(dir, { recursive: true, force: true });
});

test('--strict: lint error が無ければ通常どおり成功する', () => {
  const html = run([SAMPLE, '--strict', '--quiet']);
  assert.match(html, /^<!doctype html>/i);
});

test('--strict --json-only: JSONを出したうえで exit 3', () => {
  const r = runExpectFail(['-', '--json-only', '--strict', '--quiet'], LINT_ERROR_MD);
  assert.equal(r.status, 3);
  const meta = JSON.parse(r.stdout);
  assert.ok(meta.lint.some((l) => l.level === 'error'));
});

test('テキスト出力モードの同時指定は exit 2', () => {
  assert.equal(runExpectFail(['--print-spec', '--sample-md']).status, 2);
});

test('テキスト出力モードに入力MDを渡すと exit 2', () => {
  assert.equal(runExpectFail(['--print-spec', SAMPLE]).status, 2);
});
