/**
 * build.mjs — @mdss/cli のビルド。
 *
 * 1) theme配下13枚のCSSを main.tsx と同一順で連結し src/generated/themeCss.ts を生成
 *    ＋ app の sample.md を src/generated/sampleMd.ts として文字列化（--sample-md 用）
 *    （npx公開時に手元へ実CSSファイルが無くても動くよう、文字列としてバンドルへ取り込む）
 * 2) esbuild で src/cli.ts を dist/cli.mjs へ自己完結バンドル
 *    - @mdss/core / @mdss/app-ssr を alias でソース解決
 *    - react / react-dom(server) / zod / yaml を含め全てインライン（npxで追加install不要）
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import * as esbuild from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url)); // packages/cli
const repo = resolve(here, '..', '..'); // リポジトリルート
const appSrc = resolve(repo, 'packages/app/src');
const coreIndex = resolve(repo, 'packages/core/src/index.ts');
const appSsr = resolve(appSrc, 'ssr.tsx');

// --- 1) CSS 連結（main.tsx の統合順を単一の情報源として踏襲） ---
const CSS_ORDER = [
  'theme-vars',
  'slide-core',
  'nav-controls',
  'figure',
  'chart',
  'diagram',
  'list-view',
  'print',
  'content',
  'app',
  'steps',
  'timeline-sidelist',
  'contrast',
];
const themeDir = resolve(appSrc, 'theme');
const cssParts = CSS_ORDER.map((name) => {
  const css = readFileSync(resolve(themeDir, `${name}.css`), 'utf-8');
  return `/* ==== ${name}.css ==== */\n${css}`;
});
const cssJoined = cssParts.join('\n');
mkdirSync(resolve(here, 'src/generated'), { recursive: true });
writeFileSync(
  resolve(here, 'src/generated/themeCss.ts'),
  '// AUTO-GENERATED by build.mjs — do not edit.\n' +
    'export const THEME_CSS = ' +
    JSON.stringify(cssJoined) +
    ';\n',
  'utf-8',
);
console.log(`themeCss.ts generated (${CSS_ORDER.length} files, ${cssJoined.length} chars)`);
// --- 1-b) sample.md の埋め込み（--sample-md 用） ---
// app 側の実ファイルを唯一の情報源として文字列化する（npx公開時に手元へ実体が無くても動くため）。
const sampleMd = readFileSync(resolve(appSrc, 'samples/sample.md'), 'utf-8');
writeFileSync(
  resolve(here, 'src/generated/sampleMd.ts'),
  '// AUTO-GENERATED by build.mjs — do not edit.\n' +
    'export const SAMPLE_MD = ' +
    JSON.stringify(sampleMd) +
    ';\n',
  'utf-8',
);
console.log(`sampleMd.ts generated (${sampleMd.length} chars)`);

// --- 2) esbuild バンドル ---
const pkg = JSON.parse(readFileSync(resolve(here, 'package.json'), 'utf-8'));

await esbuild.build({
  entryPoints: [resolve(here, 'src/cli.ts')],
  outfile: resolve(here, 'dist/cli.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node18',
  jsx: 'automatic',
  minify: false,
  sourcemap: false,
  logLevel: 'info',
  // ESM出力でも react-dom/server(node) 内の require('stream') 等が動くよう
  // 実 require を createRequire で注入（esbuild ESM+node の定番対処）。shebangも同時付与。
  banner: {
    js:
      '#!/usr/bin/env node\n' +
      "import { createRequire as __mdssCreateRequire } from 'node:module';\n" +
      'const require = __mdssCreateRequire(import.meta.url);',
  },
  define: { __MDSS_CLI_VERSION__: JSON.stringify(pkg.version) },
  alias: {
    '@mdss/core': coreIndex,
    '@mdss/app-ssr': appSsr,
  },
});
console.log('bundled → dist/cli.mjs');
