#!/usr/bin/env bash
# apply-v0.3.3.sh — npm workspaces で @mdss/core を分離（モノレポ化）
# 前提: v0.3.2 の単一パッケージ構成（src/ 直下に parser/schema/components/... がある）
# 冪等: 先頭で packages/core があれば全体を [SKIP]。
#
# 方針（計画③どおり）: アンカー編集ではなく「git mv による移動 ＋ import機械置換 ＋ 設定生成」。
# import置換ロジックはPythonで実施（'./' と '../' の両相対形をカバー）。
# 全文差し替え/新規のファイル（core index・geometry・各種config・Charts.tsx）はbase64で埋め込む。
set -euo pipefail
cd "$(dirname "$0")/.."

# ---------------------------------------------------------------------------
# 0. 冪等ガード
# ---------------------------------------------------------------------------
if [ -d packages/core ]; then
  echo "[SKIP] packages/core が既に存在します。v0.3.3 は適用済みとみなします。"
  exit 0
fi

# git 管理下であることを確認（git mv を使うため）
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "[ERROR] git リポジトリ内で実行してください（git mv を使用します）"
  exit 1
fi

echo "=== v0.3.3: monorepo 化を開始します ==="

# ---------------------------------------------------------------------------
# 1. packages/{core,app}/src を作成し、ディレクトリ/ファイルを git mv
# ---------------------------------------------------------------------------
mkdir -p packages/core/src packages/app/src packages/core/src/geometry packages/app/src/parser packages/app/src/schema
git mv src/parser packages/core/src/parser
echo "[OK] moved src/parser -> packages/core/src/parser"
git mv src/schema packages/core/src/schema
echo "[OK] moved src/schema -> packages/core/src/schema"
git mv packages/core/src/parser/inline.tsx packages/app/src/parser/inline.tsx
echo "[OK] moved inline.tsx (core->app: renderInline は ReactNode のため app 残留)"
git mv packages/core/src/schema/roundtrip.test.ts packages/app/src/schema/roundtrip.test.ts
mkdir -p packages/app/src/schema/__snapshots__
git mv packages/core/src/schema/__snapshots__/roundtrip.test.ts.snap packages/app/src/schema/__snapshots__/roundtrip.test.ts.snap
rmdir packages/core/src/schema/__snapshots__ 2>/dev/null || true
echo "[OK] moved roundtrip.test.ts + snapshot (core->app: SLIDE_TEMPLATES/sample.md に依存)"
git mv packages/app/src/components/charts/charts.test.ts packages/core/src/geometry/chart.test.ts 2>/dev/null || \
  git mv src/components/charts/charts.test.ts packages/core/src/geometry/chart.test.ts
echo "[OK] moved charts.test.ts -> core/geometry/chart.test.ts"
git mv src/components packages/app/src/components
echo "[OK] moved src/components -> packages/app/src/components"
git mv src/ai packages/app/src/ai
echo "[OK] moved src/ai -> packages/app/src/ai"
git mv src/help packages/app/src/help
echo "[OK] moved src/help -> packages/app/src/help"
git mv src/hooks packages/app/src/hooks
echo "[OK] moved src/hooks -> packages/app/src/hooks"
git mv src/export packages/app/src/export
echo "[OK] moved src/export -> packages/app/src/export"
git mv src/templates packages/app/src/templates
echo "[OK] moved src/templates -> packages/app/src/templates"
git mv src/samples packages/app/src/samples
echo "[OK] moved src/samples -> packages/app/src/samples"
git mv src/theme packages/app/src/theme
echo "[OK] moved src/theme -> packages/app/src/theme"
git mv src/App.tsx packages/app/src/App.tsx
echo "[OK] moved src/App.tsx -> packages/app/src/App.tsx"
git mv src/main.tsx packages/app/src/main.tsx
echo "[OK] moved src/main.tsx -> packages/app/src/main.tsx"
git mv src/vite-env.d.ts packages/app/src/vite-env.d.ts
echo "[OK] moved src/vite-env.d.ts -> packages/app/src/vite-env.d.ts"
git mv index.html packages/app/index.html
echo "[OK] moved index.html -> packages/app/index.html"
rmdir src 2>/dev/null || true

# ルート直下の旧 vite.config.ts は packages/app/vite.config.ts に役割が移り不要（残すと紛らわしい）。
# vitest 単体実行時に誤って拾われる事故も防ぐため削除する。
if [ -f vite.config.ts ]; then
  git rm -q vite.config.ts
  echo "[OK] 旧 vite.config.ts を削除（packages/app/vite.config.ts に統合済み）"
fi

# ---------------------------------------------------------------------------
# 2. app内の import を @mdss/core へ機械置換（'./' と '../'+ の両相対形）
# ---------------------------------------------------------------------------
python3 - << 'PYEOF2'
import re, pathlib
CORE_MODULES = ['parser/types', 'parser/slideMarkdown', 'parser/slideHeader',
                'parser/deckLint', 'schema/describe', 'schema/registry']
pattern = re.compile(r"from '(\./|(?:\.\./)+)(%s)'" % '|'.join(re.escape(m) for m in CORE_MODULES))
app_root = pathlib.Path('packages/app/src')
files = list(app_root.rglob('*.ts')) + list(app_root.rglob('*.tsx'))
changed = []
for f in files:
    s = f.read_text(encoding='utf-8')
    new = pattern.sub("from '@mdss/core'", s)
    if new != s:
        f.write_text(new, encoding='utf-8')
        changed.append(str(f))
print(f"[OK] import置換: {len(changed)} files")
for c in changed:
    print("     ", c)

# roundtrip.test.ts の parseSlideMarkdown / buildX も @mdss/core へ
rt = pathlib.Path('packages/app/src/schema/roundtrip.test.ts')
s = rt.read_text(encoding='utf-8')
s = s.replace("import { parseSlideMarkdown } from '../parser/slideMarkdown';",
              "import { parseSlideMarkdown } from '@mdss/core';")
s = s.replace("import { buildTypeReferenceTable, buildConstraintRules } from './describe';",
              "import { buildTypeReferenceTable, buildConstraintRules } from '@mdss/core';")
rt.write_text(s, encoding='utf-8')
print("[OK] roundtrip.test.ts の core import を修正")
PYEOF2

# ---------------------------------------------------------------------------
# 3. 新規/全文置換ファイルを書き出し（core index・geometry・Charts.tsx・各種config）
# ---------------------------------------------------------------------------
write_b64() {
  local path="$1"; local content="$2"
  mkdir -p "$(dirname "$path")"
  echo "$content" | base64 -d > "$path"
  echo "[OK] wrote $path"
}
write_b64 'packages/core/src/index.ts' 'LyoqCiAqIEBtZHNzL2NvcmUg4oCUIE1EIFNsaWRlIFN0dWRpbyDjga5ET03pnZ7kvp3lrZjjgrPjgqLjg6njgqTjg5bjg6njg6rjgIIKICog44OR44O844K144O844O7em9k44K544Kt44O844Oe44O7ZGVja0xpbnTjg7vluqfmqJnoqIjnrpfjga7ntJTplqLmlbDjgpLmj5DkvpvjgZnjgovjgIIKICogUmVhY3QgLyBET00gLyBodG1sMmNhbnZhcyDnrYnjga7jg5bjg6njgqbjgrbkvp3lrZjjga/kuIDliIflkKvjgb7jgarjgYTvvIhOb2RlL+ODluODqeOCpuOCtuS4oeWvvuW/nO+8ieOAggogKgogKiDlhazplotBUEnjga/jgZPjga7jg5Djg6zjg6vjg5XjgqHjgqTjg6vntYznlLHjgavpm4bntITjgZnjgovjgIJhcHDlgbTjga8gYEBtZHNzL2NvcmVgIOOBi+OCieOBruOBvyBpbXBvcnQg44GZ44KL44CCCiAqLwoKLy8gLS0tIOWei+Wumue+qe+8iHR5cGVzLnRzIOOBruWFqHB1YmxpY+Wei++8iSAtLS0KZXhwb3J0ICogZnJvbSAnLi9wYXJzZXIvdHlwZXMnOwoKLy8gLS0tIOODkeODvOOCteODvCAtLS0KZXhwb3J0IHsgcGFyc2VTbGlkZU1hcmtkb3duLCBwYXJzZURpcmVjdGl2ZSwgcGFyc2VNZXJtYWlkU3Vic2V0IH0gZnJvbSAnLi9wYXJzZXIvc2xpZGVNYXJrZG93bic7CmV4cG9ydCB7IHBhcnNlU2xpZGVIZWFkZXIgfSBmcm9tICcuL3BhcnNlci9zbGlkZUhlYWRlcic7CgovLyAtLS0gZGVja0xpbnQgLS0tCmV4cG9ydCB7CiAgbGludERlY2ssCiAgc29ydExpbnRSZXN1bHRzLAogIExJTlRfTEVWRUxfT1JERVIsCiAgdHlwZSBMaW50TGV2ZWwsCiAgdHlwZSBMaW50UmVzdWx0LAp9IGZyb20gJy4vcGFyc2VyL2RlY2tMaW50JzsKCi8vIC0tLSDjgrnjgq3jg7zjg57nlLHmnaXjga5TU09U55Sf5oiQ6Zai5pWwIC0tLQpleHBvcnQgeyBidWlsZFR5cGVSZWZlcmVuY2VUYWJsZSwgYnVpbGRDb25zdHJhaW50UnVsZXMgfSBmcm9tICcuL3NjaGVtYS9kZXNjcmliZSc7CmV4cG9ydCB7IGdldEFsbFNsaWRlVHlwZU1ldGEsIHR5cGUgU2xpZGVUeXBlTWV0YSB9IGZyb20gJy4vc2NoZW1hL3JlZ2lzdHJ5JzsKCi8vIC0tLSDluqfmqJnoqIjnrpfjg7vmlbDlgKTmlbTlvaLjga7ntJTplqLmlbAgLS0tCmV4cG9ydCB7IGRvbnV0U2VnbWVudFBhdGgsIGZvcm1hdFZhbHVlIH0gZnJvbSAnLi9nZW9tZXRyeS9jaGFydCc7Cg=='
write_b64 'packages/core/src/geometry/chart.ts' 'LyoqCiAqIGdlb21ldHJ5L2NoYXJ0LnRzIOKAlCBjaGFydOaPj+eUu+OBruW6p+aomeioiOeul+ODu+aVsOWApOaVtOW9ouOBrue0lOmWouaVsO+8iERPTemdnuS+neWtmO+8ieOAggogKiBDaGFydHMudHN477yIYXBw5YG044GuSlNY57WE44G/56uL44Gm77yJ44GL44KJ5bqn5qiZ44Ot44K444OD44Kv44Gu44G/44KS5YiH44KK5Ye644GX44Gf44KC44Gu44CCCiAqIHYwLjbjga5DTEkvUFBUWOetieOAgVJlYWN06Z2e5L6d5a2Y44Gu55Kw5aKD44Gn44KC5ZCM44GY5bqn5qiZ6KiI566X44KS5L2/44GI44KL44KI44GG44Gr44GZ44KL44Gf44KB44Gu5Zyf5Y+w44CCCiAqLwoKLyoqCiAqIOODieODvOODiuODhC/lhoblvKfjga5TVkfjg5HjgrnmloflrZfliJfjgpLnlJ/miJDjgZnjgovjgIIKICogMTLmmYLmlrnlkJHotbfngrnjg7vmmYLoqIjlm57jgorjgILop5Lluqbjga/jg6njgrjjgqLjg7PvvIgwID0gMTLmmYLvvInjgIIKICovCmV4cG9ydCBmdW5jdGlvbiBkb251dFNlZ21lbnRQYXRoKAogIGN4OiBudW1iZXIsCiAgY3k6IG51bWJlciwKICByT3V0ZXI6IG51bWJlciwKICBySW5uZXI6IG51bWJlciwKICBzdGFydEFuZ2xlOiBudW1iZXIsCiAgZW5kQW5nbGU6IG51bWJlciwKKTogc3RyaW5nIHsKICBjb25zdCBsYXJnZSA9IGVuZEFuZ2xlIC0gc3RhcnRBbmdsZSA+IE1hdGguUEkgPyAxIDogMDsKICBjb25zdCBwID0gKHI6IG51bWJlciwgYTogbnVtYmVyKSA9PiAoewogICAgeDogY3ggKyByICogTWF0aC5zaW4oYSksCiAgICB5OiBjeSAtIHIgKiBNYXRoLmNvcyhhKSwKICB9KTsKICBjb25zdCBvMSA9IHAock91dGVyLCBzdGFydEFuZ2xlKTsKICBjb25zdCBvMiA9IHAock91dGVyLCBlbmRBbmdsZSk7CiAgY29uc3QgaTEgPSBwKHJJbm5lciwgZW5kQW5nbGUpOwogIGNvbnN0IGkyID0gcChySW5uZXIsIHN0YXJ0QW5nbGUpOwogIHJldHVybiBbCiAgICBgTSR7bzEueC50b0ZpeGVkKDIpfSwke28xLnkudG9GaXhlZCgyKX1gLAogICAgYEEke3JPdXRlcn0sJHtyT3V0ZXJ9IDAgJHtsYXJnZX0gMSAke28yLngudG9GaXhlZCgyKX0sJHtvMi55LnRvRml4ZWQoMil9YCwKICAgIGBMJHtpMS54LnRvRml4ZWQoMil9LCR7aTEueS50b0ZpeGVkKDIpfWAsCiAgICBgQSR7cklubmVyfSwke3JJbm5lcn0gMCAke2xhcmdlfSAwICR7aTIueC50b0ZpeGVkKDIpfSwke2kyLnkudG9GaXhlZCgyKX1gLAogICAgJ1onLAogIF0uam9pbignICcpOwp9CgovKiog5pWw5YCk44KS5pel5pys6Kqe44Ot44Kx44O844Or44Gn5pW05b2i77yIMeS4hy8x5YSE44Gn5Y2Y5L2N5LuY5LiO77yJ44CCICovCmV4cG9ydCBmdW5jdGlvbiBmb3JtYXRWYWx1ZSh2OiBudW1iZXIpOiBzdHJpbmcgewogIGlmIChNYXRoLmFicyh2KSA+PSAxMDAwMDAwMDApCiAgICByZXR1cm4gYCR7KHYgLyAxMDAwMDAwMDApLnRvTG9jYWxlU3RyaW5nKCdqYS1KUCcsIHsgbWF4aW11bUZyYWN0aW9uRGlnaXRzOiAxIH0pfeWEhGA7CiAgaWYgKE1hdGguYWJzKHYpID49IDEwMDAwKQogICAgcmV0dXJuIGAkeyh2IC8gMTAwMDApLnRvTG9jYWxlU3RyaW5nKCdqYS1KUCcsIHsgbWF4aW11bUZyYWN0aW9uRGlnaXRzOiAxIH0pfeS4h2A7CiAgcmV0dXJuIHYudG9Mb2NhbGVTdHJpbmcoJ2phLUpQJyk7Cn0K'
write_b64 'packages/core/src/geometry/chart.test.ts' 'aW1wb3J0IHsgZGVzY3JpYmUsIGV4cGVjdCwgaXQgfSBmcm9tICd2aXRlc3QnOwppbXBvcnQgeyBkb251dFNlZ21lbnRQYXRoLCBmb3JtYXRWYWx1ZSB9IGZyb20gJy4vY2hhcnQnOwoKZGVzY3JpYmUoJ2RvbnV0U2VnbWVudFBhdGgnLCAoKSA9PiB7CiAgaXQoJzEy5pmC6LW354K544O75pmC6KiI5Zue44KK44Gu44OR44K544KS55Sf5oiQ44GZ44KLJywgKCkgPT4gewogICAgLy8gMCDihpIgOTDluqbvvIjlj7PkuIo05YiG44GuMe+8iQogICAgY29uc3QgcCA9IGRvbnV0U2VnbWVudFBhdGgoMjYwLCAxODAsIDExMCwgNjAsIDAsIE1hdGguUEkgLyAyKTsKICAgIGV4cGVjdChwLnN0YXJ0c1dpdGgoJ00yNjAuMDAsNzAuMDAnKSkudG9CZSh0cnVlKTsgLy8g5aSW5ZGoMTLmmYLkvY3nva4KICAgIGV4cGVjdChwKS50b0NvbnRhaW4oJ0ExMTAsMTEwIDAgMCAxIDM3MC4wMCwxODAuMDAnKTsgLy8g5aSW5ZGoM+aZguS9jee9ruOBuOaZguioiOWbnuOCigogIH0pOwogIGl0KCcxODDluqbotoXjga8gbGFyZ2UtYXJjIOODleODqeOCsOOBjOeri+OBpCcsICgpID0+IHsKICAgIGNvbnN0IHAgPSBkb251dFNlZ21lbnRQYXRoKDAsIDAsIDEwMCwgNTAsIDAsIE1hdGguUEkgKiAxLjUpOwogICAgZXhwZWN0KHApLnRvQ29udGFpbignQTEwMCwxMDAgMCAxIDEnKTsKICB9KTsKfSk7CgpkZXNjcmliZSgnZm9ybWF0VmFsdWUnLCAoKSA9PiB7CiAgaXQoJ+S4h+ODu+WEhOWNmOS9jeOBq+S4uOOCgeOCiycsICgpID0+IHsKICAgIGV4cGVjdChmb3JtYXRWYWx1ZSg5NTAwMDAwMCkpLnRvQmUoJzksNTAw5LiHJyk7CiAgICBleHBlY3QoZm9ybWF0VmFsdWUoMTUwMDAwMDAwKSkudG9CZSgnMS415YSEJyk7CiAgICBleHBlY3QoZm9ybWF0VmFsdWUoMzIwKSkudG9CZSgnMzIwJyk7CiAgfSk7Cn0pOwoK'
write_b64 'packages/core/package.json' 'ewogICJuYW1lIjogIkBtZHNzL2NvcmUiLAogICJ2ZXJzaW9uIjogIjAuMy4zIiwKICAicHJpdmF0ZSI6IHRydWUsCiAgInR5cGUiOiAibW9kdWxlIiwKICAiZGVzY3JpcHRpb24iOiAiTUQgU2xpZGUgU3R1ZGlvIOOBrkRPTemdnuS+neWtmOOCs+OCouODqeOCpOODluODqeODqu+8iOODkeODvOOCteODvOODu+OCueOCreODvOODnuODu+W6p+aomeioiOeul++8iSIsCiAgIm1haW4iOiAiLi9zcmMvaW5kZXgudHMiLAogICJ0eXBlcyI6ICIuL3NyYy9pbmRleC50cyIsCiAgImV4cG9ydHMiOiB7CiAgICAiLiI6ICIuL3NyYy9pbmRleC50cyIKICB9LAogICJzY3JpcHRzIjogewogICAgImJ1aWxkIjogInRzYyAtcCB0c2NvbmZpZy5qc29uIC0tbm9FbWl0IiwKICAgICJ0ZXN0IjogInZpdGVzdCBydW4iCiAgfSwKICAiZGVwZW5kZW5jaWVzIjogewogICAgInlhbWwiOiAiXjIuNS4wIiwKICAgICJ6b2QiOiAiXjQuNC4zIgogIH0sCiAgImRldkRlcGVuZGVuY2llcyI6IHsKICAgICJ2aXRlc3QiOiAiXjQuMS4xMCIKICB9Cn0K'
write_b64 'packages/core/tsconfig.json' 'ewogICJjb21waWxlck9wdGlvbnMiOiB7CiAgICAidGFyZ2V0IjogIkVTMjAyMCIsCiAgICAibGliIjogWwogICAgICAiRVMyMDIwIgogICAgXSwKICAgICJtb2R1bGUiOiAiRVNOZXh0IiwKICAgICJza2lwTGliQ2hlY2siOiB0cnVlLAogICAgIm1vZHVsZVJlc29sdXRpb24iOiAiYnVuZGxlciIsCiAgICAiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnMiOiB0cnVlLAogICAgInJlc29sdmVKc29uTW9kdWxlIjogdHJ1ZSwKICAgICJpc29sYXRlZE1vZHVsZXMiOiB0cnVlLAogICAgInN0cmljdCI6IHRydWUsCiAgICAibm9GYWxsdGhyb3VnaENhc2VzSW5Td2l0Y2giOiB0cnVlLAogICAgInR5cGVzIjogWwogICAgICAidml0ZXN0L2dsb2JhbHMiCiAgICBdLAogICAgIm5vRW1pdCI6IHRydWUKICB9LAogICJpbmNsdWRlIjogWwogICAgInNyYyIKICBdCn0K'
write_b64 'packages/core/vitest.config.ts' 'aW1wb3J0IHsgZGVmaW5lQ29uZmlnIH0gZnJvbSAndml0ZXN0L2NvbmZpZyc7CgovLyBAbWRzcy9jb3JlIOOBr0RPTemdnuS+neWtmOOAgm5vZGXnkrDlooPljZjkvZPjgafjg4bjgrnjg4jjgYzpgJrjgovjgZPjgajjgpLmi4Xkv53jgZnjgovjgIIKZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29uZmlnKHsKICB0ZXN0OiB7CiAgICBlbnZpcm9ubWVudDogJ25vZGUnLAogICAgaW5jbHVkZTogWydzcmMvKiovKi50ZXN0LnRzJ10sCiAgICBleGNsdWRlOiBbJ25vZGVfbW9kdWxlcy8qKiddLAogIH0sCn0pOwo='
write_b64 'packages/app/package.json' 'ewogICJuYW1lIjogIkBtZHNzL2FwcCIsCiAgInZlcnNpb24iOiAiMC4zLjMiLAogICJwcml2YXRlIjogdHJ1ZSwKICAidHlwZSI6ICJtb2R1bGUiLAogICJkZXNjcmlwdGlvbiI6ICJNRCBTbGlkZSBTdHVkaW8g44GuUmVhY3TjgqLjg5fjg6rvvIhAbWRzcy9jb3JlIOOBq+S+neWtmO+8iSIsCiAgInNjcmlwdHMiOiB7CiAgICAiZGV2IjogInZpdGUiLAogICAgImJ1aWxkIjogInRzYyAtcCB0c2NvbmZpZy5qc29uIC0tbm9FbWl0ICYmIHZpdGUgYnVpbGQiLAogICAgInByZXZpZXciOiAidml0ZSBwcmV2aWV3IiwKICAgICJ0ZXN0IjogInZpdGVzdCBydW4iCiAgfSwKICAiZGVwZW5kZW5jaWVzIjogewogICAgIkBtZHNzL2NvcmUiOiAiKiIsCiAgICAiaHRtbDJjYW52YXMiOiAiXjEuNC4xIiwKICAgICJqc3ppcCI6ICJeMy4xMC4xIiwKICAgICJyZWFjdCI6ICJeMTguMy4xIiwKICAgICJyZWFjdC1kb20iOiAiXjE4LjMuMSIKICB9LAogICJkZXZEZXBlbmRlbmNpZXMiOiB7CiAgICAiQHR5cGVzL3JlYWN0IjogIl4xOC4zLjMiLAogICAgIkB0eXBlcy9yZWFjdC1kb20iOiAiXjE4LjMuMCIsCiAgICAiQHZpdGVqcy9wbHVnaW4tcmVhY3QiOiAiXjYuMC4zIiwKICAgICJAdml0ZXN0L2NvdmVyYWdlLXY4IjogIl40LjEuMTAiLAogICAgInZpdGUiOiAiXjguMS40IiwKICAgICJ2aXRlc3QiOiAiXjQuMS4xMCIKICB9Cn0K'
write_b64 'packages/app/tsconfig.json' 'ewogICJjb21waWxlck9wdGlvbnMiOiB7CiAgICAidGFyZ2V0IjogIkVTMjAyMCIsCiAgICAidXNlRGVmaW5lRm9yQ2xhc3NGaWVsZHMiOiB0cnVlLAogICAgImxpYiI6IFsKICAgICAgIkVTMjAyMCIsCiAgICAgICJET00iLAogICAgICAiRE9NLkl0ZXJhYmxlIgogICAgXSwKICAgICJtb2R1bGUiOiAiRVNOZXh0IiwKICAgICJza2lwTGliQ2hlY2siOiB0cnVlLAogICAgIm1vZHVsZVJlc29sdXRpb24iOiAiYnVuZGxlciIsCiAgICAiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnMiOiB0cnVlLAogICAgInJlc29sdmVKc29uTW9kdWxlIjogdHJ1ZSwKICAgICJpc29sYXRlZE1vZHVsZXMiOiB0cnVlLAogICAgImpzeCI6ICJyZWFjdC1qc3giLAogICAgInN0cmljdCI6IHRydWUsCiAgICAibm9GYWxsdGhyb3VnaENhc2VzSW5Td2l0Y2giOiB0cnVlLAogICAgInR5cGVzIjogWwogICAgICAidml0ZS9jbGllbnQiLAogICAgICAidml0ZXN0L2dsb2JhbHMiCiAgICBdLAogICAgInBhdGhzIjogewogICAgICAiQG1kc3MvY29yZSI6IFsKICAgICAgICAiLi4vY29yZS9zcmMvaW5kZXgudHMiCiAgICAgIF0KICAgIH0sCiAgICAibm9FbWl0IjogdHJ1ZQogIH0sCiAgImluY2x1ZGUiOiBbCiAgICAic3JjIgogIF0KfQo='
write_b64 'packages/app/vite.config.ts' 'aW1wb3J0IHsgZGVmaW5lQ29uZmlnIH0gZnJvbSAndml0ZSc7CmltcG9ydCByZWFjdCBmcm9tICdAdml0ZWpzL3BsdWdpbi1yZWFjdCc7CmltcG9ydCB7IGZpbGVVUkxUb1BhdGggfSBmcm9tICdub2RlOnVybCc7CgovLyBHaXRIdWIgUGFnZXPvvIjjg5fjg63jgrjjgqfjgq/jg4jjgrXjgqTjg4jvvInphY3kv6Hjga7jgZ/jgoHnm7jlr77jg5Hjgrnjgafjg5Pjg6vjg4njgZnjgovjgIIKLy8g44Or44O844K/44O844KS5L2/44KP44Gq44GEU1BB44Gq44Gu44GnIGJhc2U6ICcuLycg44Gn5YWo55Kw5aKD44Gr5a++5b+c44CCCi8vIEBtZHNzL2NvcmUg44Gv44K944O844K555u05o6l5Y+C54Wn77yId29ya3NwYWNl77yJ44Gq44Gu44GnIGFsaWFzIOOBpyBjb3JlL3NyYyDjgpLmjIfjgZnjgIIKZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29uZmlnKHsKICBiYXNlOiAnLi8nLAogIHBsdWdpbnM6IFtyZWFjdCgpXSwKICByZXNvbHZlOiB7CiAgICBhbGlhczogewogICAgICAnQG1kc3MvY29yZSc6IGZpbGVVUkxUb1BhdGgobmV3IFVSTCgnLi4vY29yZS9zcmMvaW5kZXgudHMnLCBpbXBvcnQubWV0YS51cmwpKSwKICAgIH0sCiAgfSwKICB0ZXN0OiB7CiAgICBlbnZpcm9ubWVudDogJ25vZGUnLAogICAgaW5jbHVkZTogWydzcmMvKiovKi50ZXN0LnRzJ10sCiAgICBleGNsdWRlOiBbJ2UyZS8qKicsICdub2RlX21vZHVsZXMvKionXSwKICAgIGNvdmVyYWdlOiB7CiAgICAgIHByb3ZpZGVyOiAndjgnLAogICAgICByZXBvcnRlcjogWyd0ZXh0JywgJ2h0bWwnXSwKICAgICAgcmVwb3J0c0RpcmVjdG9yeTogJy4vY292ZXJhZ2UnLAogICAgfSwKICB9LAp9IGFzIG5ldmVyKTsK'
write_b64 'packages/app/index.html' 'PCFkb2N0eXBlIGh0bWw+CjxodG1sIGxhbmc9ImphIj4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9IlVURi04IiAvPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiIC8+CiAgICA8dGl0bGU+TUQgU2xpZGUgU3R1ZGlvPC90aXRsZT4KICAgIDxsaW5rIHJlbD0icHJlY29ubmVjdCIgaHJlZj0iaHR0cHM6Ly9mb250cy5nb29nbGVhcGlzLmNvbSIgLz4KICAgIDxsaW5rCiAgICAgIGhyZWY9Imh0dHBzOi8vZm9udHMuZ29vZ2xlYXBpcy5jb20vY3NzMj9mYW1pbHk9Tm90bytTYW5zK0pQOndnaHRANDAwOzUwMDs3MDAmZmFtaWx5PUpldEJyYWlucytNb25vOndnaHRANDAwOzUwMCZkaXNwbGF5PXN3YXAiCiAgICAgIHJlbD0ic3R5bGVzaGVldCIKICAgIC8+CiAgPC9oZWFkPgogIDxib2R5PgogICAgPGRpdiBpZD0icm9vdCI+PC9kaXY+CiAgICA8c2NyaXB0IHR5cGU9Im1vZHVsZSIgc3JjPSIvc3JjL21haW4udHN4Ij48L3NjcmlwdD4KICA8L2JvZHk+CjwvaHRtbD4KCg=='
write_b64 'packages/app/src/components/charts/Charts.tsx' 'LyoqCiAqIENoYXJ0cy50c3gg4oCUIGNoYXJ0LWdlbmVyYXRpb24ubWQg44Gu5bqn5qiZ44OG44O844OW44Or44Gr5Z+644Gl44GP5rG65a6a6KuW55qEU1ZH55Sf5oiQ44CCCiAqIC0gdmlld0JveCA3MjDDlzM2MOOAgeacrOaWh+mgmOWfnyDiiZIgMTYwLTY4MCwgNTAtMzEwCiAqIC0g6Imy44Gv44OP44O844OJ44Kz44O844OJ56aB5q2iOiBjaGFydC1zZXJpZXMtTiAvIGNoYXJ0LWxpbmUtTiDjgq/jg6njgrnntYznlLHvvIhDU1PlpInmlbDov73lvpPvvIkKICogLSDjgr/jgqTjg4jjg6vjg7vou7jjg6njg5njg6vjg7vmlbDlgKTjg6njg5njg6vjg7vlh7rlhbjjga/lv4XpoIjopoHntKDjgajjgZfjgabluLjjgavmj4/nlLsKICovCmltcG9ydCB0eXBlIHsgQ2hhcnRCbG9jaywgQ29tcGFyaXNvbkNoYXJ0QmxvY2sgfSBmcm9tICdAbWRzcy9jb3JlJzsKaW1wb3J0IHsgZG9udXRTZWdtZW50UGF0aCwgZm9ybWF0VmFsdWUgfSBmcm9tICdAbWRzcy9jb3JlJzsKCi8vIOW+jOaWueS6kuaPmzog5pei5a2Y44GuIGBpbXBvcnQgeyBkb251dFNlZ21lbnRQYXRoLCBmb3JtYXRWYWx1ZSB9IGZyb20gJy4vQ2hhcnRzJ2Ag44KS57at5oyB44GZ44KL44Gf44KBIHJlLWV4cG9ydOOAggpleHBvcnQgeyBkb251dFNlZ21lbnRQYXRoLCBmb3JtYXRWYWx1ZSB9OwoKY29uc3QgVkIgPSB7IHc6IDcyMCwgaDogMzYwIH07CgpmdW5jdGlvbiBDaGFydEZyYW1lKHsKICB0aXRsZSwKICBzb3VyY2UsCiAgY2hpbGRyZW4sCn06IHsKICB0aXRsZTogc3RyaW5nOwogIHNvdXJjZTogeyBuYW1lOiBzdHJpbmc7IHVybD86IHN0cmluZyB9OwogIGNoaWxkcmVuOiBSZWFjdC5SZWFjdE5vZGU7Cn0pIHsKICByZXR1cm4gKAogICAgPHN2ZwogICAgICB2aWV3Qm94PXtgMCAwICR7VkIud30gJHtWQi5ofWB9CiAgICAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgICAgY2xhc3NOYW1lPSJjaGFydC1zdmciCiAgICAgIHJvbGU9ImltZyIKICAgID4KICAgICAgPHRpdGxlPnt0aXRsZX08L3RpdGxlPgogICAgICA8dGV4dCB4PXtWQi53IC8gMn0geT17Mjh9IGNsYXNzTmFtZT0iY2hhcnQtdGl0bGUiIHRleHRBbmNob3I9Im1pZGRsZSI+CiAgICAgICAge3RpdGxlfQogICAgICA8L3RleHQ+CiAgICAgIHtjaGlsZHJlbn0KICAgICAgPHRleHQgeD17VkIudyAtIDEwfSB5PXtWQi5oIC0gOH0gY2xhc3NOYW1lPSJjaGFydC1zb3VyY2UiIHRleHRBbmNob3I9ImVuZCI+CiAgICAgICAg5Ye65YW4OiB7c291cmNlLm5hbWV9CiAgICAgIDwvdGV4dD4KICAgIDwvc3ZnPgogICk7Cn0KCi8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQovLyDmqKrmo5LjgrDjg6njg5U6IHdpZHRoID0gKHZhbCAvIG1heCkgw5cgNDgw44CB44Kr44OG44K044Oq6KGM44Gv5Zu65a6a6ZaT6ZqUCi8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQoKZXhwb3J0IGZ1bmN0aW9uIEJhckNoYXJ0U3ZnKHsgY2hhcnQgfTogeyBjaGFydDogQ2hhcnRCbG9jayB9KSB7CiAgY29uc3QgZGF0YSA9IGNoYXJ0LmRhdGE7CiAgY29uc3QgbWF4ID0gTWF0aC5tYXgoLi4uZGF0YS5tYXAoKGQpID0+IGQudmFsdWUpLCAxKTsKICBjb25zdCB4MCA9IDE2MDsKICBjb25zdCBhcmVhVG9wID0gNTY7CiAgY29uc3QgYXJlYUJvdHRvbSA9IDMwNjsKICBjb25zdCByb3dIID0gKGFyZWFCb3R0b20gLSBhcmVhVG9wKSAvIGRhdGEubGVuZ3RoOwogIGNvbnN0IGJhckggPSBNYXRoLm1pbigzMCwgcm93SCAqIDAuNTUpOwogIHJldHVybiAoCiAgICA8Q2hhcnRGcmFtZSB0aXRsZT17Y2hhcnQudGl0bGV9IHNvdXJjZT17Y2hhcnQuc291cmNlfT4KICAgICAge2RhdGEubWFwKChkLCBpKSA9PiB7CiAgICAgICAgY29uc3QgeSA9IGFyZWFUb3AgKyByb3dIICogaSArIChyb3dIIC0gYmFySCkgLyAyOwogICAgICAgIGNvbnN0IHcgPSBNYXRoLm1heCgyLCAoZC52YWx1ZSAvIG1heCkgKiA0ODApOwogICAgICAgIHJldHVybiAoCiAgICAgICAgICA8ZyBrZXk9e2l9PgogICAgICAgICAgICA8dGV4dCB4PXt4MCAtIDEyfSB5PXt5ICsgYmFySCAvIDIgKyA0fSBjbGFzc05hbWU9ImNoYXJ0LWxhYmVsIiB0ZXh0QW5jaG9yPSJlbmQiPgogICAgICAgICAgICAgIHtkLmxhYmVsfQogICAgICAgICAgICA8L3RleHQ+CiAgICAgICAgICAgIDxyZWN0CiAgICAgICAgICAgICAgeD17eDB9CiAgICAgICAgICAgICAgeT17eX0KICAgICAgICAgICAgICB3aWR0aD17d30KICAgICAgICAgICAgICBoZWlnaHQ9e2Jhckh9CiAgICAgICAgICAgICAgcng9ezN9CiAgICAgICAgICAgICAgY2xhc3NOYW1lPXtgY2hhcnQtc2VyaWVzLSR7KGkgJSA1KSArIDF9YH0KICAgICAgICAgICAgLz4KICAgICAgICAgICAgPHRleHQgeD17eDAgKyB3ICsgOH0geT17eSArIGJhckggLyAyICsgNH0gY2xhc3NOYW1lPSJjaGFydC12YWx1ZSI+CiAgICAgICAgICAgICAge2Zvcm1hdFZhbHVlKGQudmFsdWUpfQogICAgICAgICAgICAgIHtjaGFydC51bml0ID8/ICcnfQogICAgICAgICAgICA8L3RleHQ+CiAgICAgICAgICA8L2c+CiAgICAgICAgKTsKICAgICAgfSl9CiAgICAgIDx0ZXh0IHg9e1ZCLncgLyAyfSB5PXszNDB9IGNsYXNzTmFtZT0iY2hhcnQtYXhpcy1sYWJlbCIgdGV4dEFuY2hvcj0ibWlkZGxlIj4KICAgICAgICB7Y2hhcnQudW5pdCA/IGDlgKTvvIgke2NoYXJ0LnVuaXR977yJYCA6ICflgKQnfQogICAgICA8L3RleHQ+CiAgICAgIDx0ZXh0CiAgICAgICAgY2xhc3NOYW1lPSJjaGFydC1heGlzLWxhYmVsIgogICAgICAgIHRyYW5zZm9ybT0icm90YXRlKC05MCAyNCAxOTApIgogICAgICAgIHg9ezI0fQogICAgICAgIHk9ezE5MH0KICAgICAgICB0ZXh0QW5jaG9yPSJtaWRkbGUiCiAgICAgID4KICAgICAgICDpoIXnm64KICAgICAgPC90ZXh0PgogICAgPC9DaGFydEZyYW1lPgogICk7Cn0KCi8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQovLyDmipjjgoznt5o6IHggPSAxNjAgKyAoaS8oTi0xKSnDlzQ4MCwgeSA9IDI5MCAtICgodmFsLW1pbikvKG1heC1taW4pKcOXMjIwCi8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQoKZXhwb3J0IGZ1bmN0aW9uIExpbmVDaGFydFN2Zyh7IGNoYXJ0IH06IHsgY2hhcnQ6IENoYXJ0QmxvY2sgfSkgewogIGNvbnN0IGRhdGEgPSBjaGFydC5kYXRhOwogIGNvbnN0IG1heCA9IE1hdGgubWF4KC4uLmRhdGEubWFwKChkKSA9PiBkLnZhbHVlKSk7CiAgY29uc3QgbWluID0gTWF0aC5taW4oLi4uZGF0YS5tYXAoKGQpID0+IGQudmFsdWUpKTsKICBjb25zdCByYW5nZSA9IG1heCAtIG1pbiB8fCAxOwogIGNvbnN0IHB0ID0gKGk6IG51bWJlciwgdjogbnVtYmVyKSA9PiAoewogICAgeDogZGF0YS5sZW5ndGggPT09IDEgPyA0MDAgOiAxNjAgKyAoaSAvIChkYXRhLmxlbmd0aCAtIDEpKSAqIDQ4MCwKICAgIHk6IDI5MCAtICgodiAtIG1pbikgLyByYW5nZSkgKiAyMjAsCiAgfSk7CiAgY29uc3QgcG9pbnRzID0gZGF0YS5tYXAoKGQsIGkpID0+IHB0KGksIGQudmFsdWUpKTsKICBjb25zdCBwYXRoID0gcG9pbnRzCiAgICAubWFwKChwLCBpKSA9PiBgJHtpID09PSAwID8gJ00nIDogJ0wnfSR7cC54LnRvRml4ZWQoMSl9LCR7cC55LnRvRml4ZWQoMSl9YCkKICAgIC5qb2luKCcgJyk7CiAgcmV0dXJuICgKICAgIDxDaGFydEZyYW1lIHRpdGxlPXtjaGFydC50aXRsZX0gc291cmNlPXtjaGFydC5zb3VyY2V9PgogICAgICB7Lyog44Kw44Oq44OD44OJICovfQogICAgICB7WzAsIDAuNSwgMV0ubWFwKCh0KSA9PiAoCiAgICAgICAgPGxpbmUKICAgICAgICAgIGtleT17dH0KICAgICAgICAgIHgxPXsxNjB9CiAgICAgICAgICB4Mj17NjQwfQogICAgICAgICAgeTE9ezI5MCAtIHQgKiAyMjB9CiAgICAgICAgICB5Mj17MjkwIC0gdCAqIDIyMH0KICAgICAgICAgIGNsYXNzTmFtZT0iY2hhcnQtZ3JpZC1saW5lIgogICAgICAgIC8+CiAgICAgICkpfQogICAgICA8cGF0aCBkPXtwYXRofSBjbGFzc05hbWU9ImNoYXJ0LWxpbmUtMSIgZmlsbD0ibm9uZSIgLz4KICAgICAge3BvaW50cy5tYXAoKHAsIGkpID0+ICgKICAgICAgICA8ZyBrZXk9e2l9PgogICAgICAgICAgPGNpcmNsZSBjeD17cC54fSBjeT17cC55fSByPXs1fSBjbGFzc05hbWU9ImNoYXJ0LXNlcmllcy0xIiAvPgogICAgICAgICAgPHRleHQgeD17cC54fSB5PXtwLnkgLSAxMn0gY2xhc3NOYW1lPSJjaGFydC12YWx1ZSIgdGV4dEFuY2hvcj0ibWlkZGxlIj4KICAgICAgICAgICAge2Zvcm1hdFZhbHVlKGRhdGFbaV0udmFsdWUpfQogICAgICAgICAgICB7Y2hhcnQudW5pdCA/PyAnJ30KICAgICAgICAgIDwvdGV4dD4KICAgICAgICAgIDx0ZXh0IHg9e3AueH0geT17MzEyfSBjbGFzc05hbWU9ImNoYXJ0LWxhYmVsIiB0ZXh0QW5jaG9yPSJtaWRkbGUiPgogICAgICAgICAgICB7ZGF0YVtpXS5sYWJlbH0KICAgICAgICAgIDwvdGV4dD4KICAgICAgICA8L2c+CiAgICAgICkpfQogICAgICA8dGV4dCB4PXtWQi53IC8gMn0geT17MzQ0fSBjbGFzc05hbWU9ImNoYXJ0LWF4aXMtbGFiZWwiIHRleHRBbmNob3I9Im1pZGRsZSI+CiAgICAgICAg5pmC54K5CiAgICAgIDwvdGV4dD4KICAgICAgPHRleHQKICAgICAgICBjbGFzc05hbWU9ImNoYXJ0LWF4aXMtbGFiZWwiCiAgICAgICAgdHJhbnNmb3JtPSJyb3RhdGUoLTkwIDI0IDE5MCkiCiAgICAgICAgeD17MjR9CiAgICAgICAgeT17MTkwfQogICAgICAgIHRleHRBbmNob3I9Im1pZGRsZSIKICAgICAgPgogICAgICAgIHtjaGFydC51bml0ID8gYOWApO+8iCR7Y2hhcnQudW5pdH3vvIlgIDogJ+WApCd9CiAgICAgIDwvdGV4dD4KICAgIDwvQ2hhcnRGcmFtZT4KICApOwp9CgovLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KLy8g44OJ44O844OK44OEOiDkuK3lv4MoMjYwLDE4MCkg5aSW5b6EMTEwIOWGheW+hDYw44CBMTLmmYLotbfngrnjgafmmYLoqIjlm57jgooKLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgovLyBkb251dFNlZ21lbnRQYXRoIC8gZm9ybWF0VmFsdWUg44GvIEBtZHNzL2NvcmUvZ2VvbWV0cnkg44G456e76Kit44GX44CB5pyr5bC+44GnIHJlLWV4cG9ydCDjgZnjgovjgIIKCmZ1bmN0aW9uIGRvbnV0U2VnbWVudHMoCiAgZGF0YTogeyB2YWx1ZTogbnVtYmVyOyBjbGFzc05hbWU6IHN0cmluZzsgbGFiZWw6IHN0cmluZyB9W10sCiAgY3g6IG51bWJlciwKICBjeTogbnVtYmVyLAogIHJPdXRlcjogbnVtYmVyLAogIHJJbm5lcjogbnVtYmVyLAopIHsKICBjb25zdCB0b3RhbCA9IGRhdGEucmVkdWNlKChzLCBkKSA9PiBzICsgTWF0aC5tYXgoMCwgZC52YWx1ZSksIDApIHx8IDE7CiAgbGV0IGFuZ2xlID0gMDsKICByZXR1cm4gZGF0YS5tYXAoKGQsIGkpID0+IHsKICAgIGNvbnN0IHN3ZWVwID0gKE1hdGgubWF4KDAsIGQudmFsdWUpIC8gdG90YWwpICogTWF0aC5QSSAqIDI7CiAgICBjb25zdCBzZWcgPSB7CiAgICAgIGtleTogaSwKICAgICAgcGF0aDogZG9udXRTZWdtZW50UGF0aChjeCwgY3ksIHJPdXRlciwgcklubmVyLCBhbmdsZSwgYW5nbGUgKyBNYXRoLm1heChzd2VlcCAtIDAuMDA0LCAwKSksCiAgICAgIGNsYXNzTmFtZTogZC5jbGFzc05hbWUsCiAgICAgIG1pZDogYW5nbGUgKyBzd2VlcCAvIDIsCiAgICAgIHZhbHVlOiBkLnZhbHVlLAogICAgICBsYWJlbDogZC5sYWJlbCwKICAgIH07CiAgICBhbmdsZSArPSBzd2VlcDsKICAgIHJldHVybiBzZWc7CiAgfSk7Cn0KCmV4cG9ydCBmdW5jdGlvbiBEb251dENoYXJ0U3ZnKHsgY2hhcnQgfTogeyBjaGFydDogQ2hhcnRCbG9jayB9KSB7CiAgY29uc3QgY3ggPSAyNjAsCiAgICBjeSA9IDE4MCwKICAgIHJPID0gMTEwLAogICAgckkgPSA2MDsKICBjb25zdCBzZWdzID0gZG9udXRTZWdtZW50cygKICAgIGNoYXJ0LmRhdGEubWFwKChkLCBpKSA9PiAoewogICAgICB2YWx1ZTogZC52YWx1ZSwKICAgICAgY2xhc3NOYW1lOiBgY2hhcnQtc2VyaWVzLSR7KGkgJSA1KSArIDF9YCwKICAgICAgbGFiZWw6IGQubGFiZWwsCiAgICB9KSksCiAgICBjeCwKICAgIGN5LAogICAgck8sCiAgICBySSwKICApOwogIGNvbnN0IHRvdGFsID0gY2hhcnQuZGF0YS5yZWR1Y2UoKHMsIGQpID0+IHMgKyBkLnZhbHVlLCAwKTsKICByZXR1cm4gKAogICAgPENoYXJ0RnJhbWUgdGl0bGU9e2NoYXJ0LnRpdGxlfSBzb3VyY2U9e2NoYXJ0LnNvdXJjZX0+CiAgICAgIHtzZWdzLm1hcCgocykgPT4gKAogICAgICAgIDxwYXRoIGtleT17cy5rZXl9IGQ9e3MucGF0aH0gY2xhc3NOYW1lPXtzLmNsYXNzTmFtZX0gLz4KICAgICAgKSl9CiAgICAgIHsvKiDmlbDlgKTjg6njg5njg6vvvIjjgrvjgrDjg6Hjg7Pjg4jlpJblgbTvvIkgKi99CiAgICAgIHtzZWdzLm1hcCgocykgPT4gewogICAgICAgIGNvbnN0IGx4ID0gY3ggKyAock8gKyAyMikgKiBNYXRoLnNpbihzLm1pZCk7CiAgICAgICAgY29uc3QgbHkgPSBjeSAtIChyTyArIDIyKSAqIE1hdGguY29zKHMubWlkKTsKICAgICAgICByZXR1cm4gKAogICAgICAgICAgPHRleHQga2V5PXtgdiR7cy5rZXl9YH0geD17bHh9IHk9e2x5ICsgNH0gY2xhc3NOYW1lPSJjaGFydC12YWx1ZSIgdGV4dEFuY2hvcj0ibWlkZGxlIj4KICAgICAgICAgICAge2Zvcm1hdFZhbHVlKHMudmFsdWUpfQogICAgICAgICAgICB7Y2hhcnQudW5pdCA/PyAnJ30KICAgICAgICAgIDwvdGV4dD4KICAgICAgICApOwogICAgICB9KX0KICAgICAgey8qIOWHoeS+i++8iOWPs+WBtO+8iSAqL30KICAgICAge2NoYXJ0LmRhdGEubWFwKChkLCBpKSA9PiAoCiAgICAgICAgPGcga2V5PXtgbCR7aX1gfT4KICAgICAgICAgIDxyZWN0CiAgICAgICAgICAgIHg9ezQ3MH0KICAgICAgICAgICAgeT17OTAgKyBpICogMzR9CiAgICAgICAgICAgIHdpZHRoPXsxNH0KICAgICAgICAgICAgaGVpZ2h0PXsxNH0KICAgICAgICAgICAgcng9ezN9CiAgICAgICAgICAgIGNsYXNzTmFtZT17YGNoYXJ0LXNlcmllcy0keyhpICUgNSkgKyAxfWB9CiAgICAgICAgICAvPgogICAgICAgICAgPHRleHQgeD17NDkyfSB5PXsxMDIgKyBpICogMzR9IGNsYXNzTmFtZT0iY2hhcnQtbGVnZW5kIj4KICAgICAgICAgICAge2QubGFiZWx977yIe3RvdGFsID8gTWF0aC5yb3VuZCgoZC52YWx1ZSAvIHRvdGFsKSAqIDEwMCkgOiAwfSXvvIkKICAgICAgICAgIDwvdGV4dD4KICAgICAgICA8L2c+CiAgICAgICkpfQogICAgPC9DaGFydEZyYW1lPgogICk7Cn0KCi8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQovLyBjb21wYXJpc29uLWNoYXJ0OiBCZWZvcmUoMTkwLDE3NSkgLyBBZnRlcig1MzAsMTc1KeOAgeWkluW+hDEwMOODu+WGheW+hDU1Ci8vIOWHoeS+i+ODhuODvOODluODqyB5PTMwMOOAnDMyNuOAgeefouWNsCAoMzAwLDE3NSnihpIoNDEwLDE3NSkKLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgpleHBvcnQgZnVuY3Rpb24gQ29tcGFyaXNvbkRvbnV0U3ZnKHsgY2hhcnQgfTogeyBjaGFydDogQ29tcGFyaXNvbkNoYXJ0QmxvY2sgfSkgewogIGNvbnN0IGNscyA9IChjOiBzdHJpbmcpID0+IChjID09PSAnbmV1dHJhbCcgPyAnY2hhcnQtbmV1dHJhbCcgOiBgY2hhcnQtc2VyaWVzLSR7Y31gKTsKICBjb25zdCBiZWZvcmUgPSBkb251dFNlZ21lbnRzKAogICAgY2hhcnQuZGF0YS5tYXAoKGQpID0+ICh7IHZhbHVlOiBkLmJlZm9yZSwgY2xhc3NOYW1lOiBjbHMoZC5jbGFzcyksIGxhYmVsOiBkLmxhYmVsIH0pKSwKICAgIDE5MCwKICAgIDE3NSwKICAgIDEwMCwKICAgIDU1LAogICk7CiAgY29uc3QgYWZ0ZXIgPSBkb251dFNlZ21lbnRzKAogICAgY2hhcnQuZGF0YS5tYXAoKGQpID0+ICh7IHZhbHVlOiBkLmFmdGVyLCBjbGFzc05hbWU6IGNscyhkLmNsYXNzKSwgbGFiZWw6IGQubGFiZWwgfSkpLAogICAgNTMwLAogICAgMTc1LAogICAgMTAwLAogICAgNTUsCiAgKTsKICBjb25zdCBsZWdlbmRDb2xzID0gY2hhcnQuZGF0YS5zbGljZSgwLCA0KTsKICByZXR1cm4gKAogICAgPHN2ZyB2aWV3Qm94PSIwIDAgNzIwIDM2MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiBjbGFzc05hbWU9ImNoYXJ0LXN2ZyIgcm9sZT0iaW1nIj4KICAgICAgPHRpdGxlPgogICAgICAgIHtjaGFydC5sYWJlbHMuYmVmb3JlfSAvIHtjaGFydC5sYWJlbHMuYWZ0ZXJ9IOavlOi8gwogICAgICA8L3RpdGxlPgogICAgICA8ZGVmcz4KICAgICAgICA8bWFya2VyCiAgICAgICAgICBpZD0iYmEtYXJyb3ciCiAgICAgICAgICB2aWV3Qm94PSIwIDAgMTAgMTAiCiAgICAgICAgICByZWZYPSI5IgogICAgICAgICAgcmVmWT0iNSIKICAgICAgICAgIG1hcmtlcldpZHRoPSI3IgogICAgICAgICAgbWFya2VySGVpZ2h0PSI3IgogICAgICAgICAgb3JpZW50PSJhdXRvIgogICAgICAgID4KICAgICAgICAgIDxwYXRoIGQ9Ik0wLDAgTDEwLDUgTDAsMTAgeiIgY2xhc3NOYW1lPSJjaGFydC1hcnJvd2hlYWQiIC8+CiAgICAgICAgPC9tYXJrZXI+CiAgICAgIDwvZGVmcz4KICAgICAgPHRleHQgeD17MTkwfSB5PXszMH0gY2xhc3NOYW1lPSJjaGFydC10aXRsZSIgdGV4dEFuY2hvcj0ibWlkZGxlIj4KICAgICAgICB7Y2hhcnQubGFiZWxzLmJlZm9yZX0KICAgICAgPC90ZXh0PgogICAgICA8dGV4dCB4PXs1MzB9IHk9ezMwfSBjbGFzc05hbWU9ImNoYXJ0LXRpdGxlIiB0ZXh0QW5jaG9yPSJtaWRkbGUiPgogICAgICAgIHtjaGFydC5sYWJlbHMuYWZ0ZXJ9CiAgICAgIDwvdGV4dD4KICAgICAge2JlZm9yZS5tYXAoKHMpID0+ICgKICAgICAgICA8cGF0aCBrZXk9e2BiJHtzLmtleX1gfSBkPXtzLnBhdGh9IGNsYXNzTmFtZT17cy5jbGFzc05hbWV9IC8+CiAgICAgICkpfQogICAgICB7YWZ0ZXIubWFwKChzKSA9PiAoCiAgICAgICAgPHBhdGgga2V5PXtgYSR7cy5rZXl9YH0gZD17cy5wYXRofSBjbGFzc05hbWU9e3MuY2xhc3NOYW1lfSAvPgogICAgICApKX0KICAgICAgPHRleHQgeD17MTkwfSB5PXsxNzB9IGNsYXNzTmFtZT0iY2hhcnQtY2VudGVyLWJpZyIgdGV4dEFuY2hvcj0ibWlkZGxlIj4KICAgICAgICB7Y2hhcnQuY2VudGVyLmJlZm9yZX0KICAgICAgPC90ZXh0PgogICAgICA8dGV4dCB4PXs1MzB9IHk9ezE3MH0gY2xhc3NOYW1lPSJjaGFydC1jZW50ZXItYmlnIiB0ZXh0QW5jaG9yPSJtaWRkbGUiPgogICAgICAgIHtjaGFydC5jZW50ZXIuYWZ0ZXJ9CiAgICAgIDwvdGV4dD4KICAgICAgPHBhdGggZD0iTTMwMCwxNzUgTDQxMCwxNzUiIGNsYXNzTmFtZT0iY2hhcnQtYmEtYXJyb3ciIG1hcmtlckVuZD0idXJsKCNiYS1hcnJvdykiIC8+CiAgICAgIHsvKiDlh6Hkvovjg4bjg7zjg5bjg6vvvIgy5YiXIMOXIDLooYzvvIkgKi99CiAgICAgIHtsZWdlbmRDb2xzLm1hcCgoZCwgaSkgPT4gewogICAgICAgIGNvbnN0IGNvbCA9IGkgJSAyOwogICAgICAgIGNvbnN0IHJvdyA9IE1hdGguZmxvb3IoaSAvIDIpOwogICAgICAgIGNvbnN0IGJ4ID0gY29sID09PSAwID8gNzAgOiAyNzA7CiAgICAgICAgY29uc3QgeSA9IDMwMCArIHJvdyAqIDI2OwogICAgICAgIHJldHVybiAoCiAgICAgICAgICA8ZyBrZXk9e2BsZyR7aX1gfT4KICAgICAgICAgICAgPHJlY3QgeD17Ynh9IHk9e3kgLSAxMX0gd2lkdGg9ezE0fSBoZWlnaHQ9ezE0fSByeD17M30gY2xhc3NOYW1lPXtjbHMoZC5jbGFzcyl9IC8+CiAgICAgICAgICAgIDx0ZXh0IHg9e2J4ICsgMjJ9IHk9e3l9IGNsYXNzTmFtZT0iY2hhcnQtbGVnZW5kIj4KICAgICAgICAgICAgICB7ZC5sYWJlbH06IHtmb3JtYXRWYWx1ZShkLmJlZm9yZSl9IOKGkiB7Zm9ybWF0VmFsdWUoZC5hZnRlcil9CiAgICAgICAgICAgIDwvdGV4dD4KICAgICAgICAgIDwvZz4KICAgICAgICApOwogICAgICB9KX0KICAgICAgPHRleHQgeD17NzEwfSB5PXszNTJ9IGNsYXNzTmFtZT0iY2hhcnQtc291cmNlIiB0ZXh0QW5jaG9yPSJlbmQiPgogICAgICAgIOWHuuWFuDoge2NoYXJ0LnNvdXJjZS5uYW1lfQogICAgICA8L3RleHQ+CiAgICA8L3N2Zz4KICApOwp9CgovLyBmb3JtYXRWYWx1ZSDjga8gQG1kc3MvY29yZS9nZW9tZXRyeSDjgbjnp7voqK3vvIjmnKvlsL7jgacgcmUtZXhwb3J077yJ44CCCg=='
write_b64 'package.json' 'ewogICJuYW1lIjogIm1kLXNsaWRlLXN0dWRpby1tb25vcmVwbyIsCiAgInZlcnNpb24iOiAiMC4zLjMiLAogICJwcml2YXRlIjogdHJ1ZSwKICAidHlwZSI6ICJtb2R1bGUiLAogICJkZXNjcmlwdGlvbiI6ICJNYXJrZG93buWOn+eov+OBi+OCieOCueODqeOCpOODiUhUTUzvvI9QREbvvI9QTkfjgpLnlJ/miJDjgZnjgotXZWLjgqLjg5fjg6rvvIhtb25vcmVwb++8iSIsCiAgIndvcmtzcGFjZXMiOiBbCiAgICAicGFja2FnZXMvY29yZSIsCiAgICAicGFja2FnZXMvYXBwIgogIF0sCiAgInNjcmlwdHMiOiB7CiAgICAiZGV2IjogIm5wbSBydW4gZGV2IC13IEBtZHNzL2FwcCIsCiAgICAiYnVpbGQiOiAibnBtIHJ1biBidWlsZCAtdyBAbWRzcy9jb3JlICYmIG5wbSBydW4gYnVpbGQgLXcgQG1kc3MvYXBwIiwKICAgICJwcmV2aWV3IjogIm5wbSBydW4gcHJldmlldyAtdyBAbWRzcy9hcHAiLAogICAgImxpbnQiOiAiZXNsaW50IHBhY2thZ2VzLyovc3JjIiwKICAgICJsaW50OmZpeCI6ICJlc2xpbnQgcGFja2FnZXMvKi9zcmMgLS1maXgiLAogICAgImZvcm1hdCI6ICJwcmV0dGllciAtLXdyaXRlIFwicGFja2FnZXMvKi9zcmMvKiovKi57dHMsdHN4LGNzc31cIiIsCiAgICAiZm9ybWF0OmNoZWNrIjogInByZXR0aWVyIC0tY2hlY2sgXCJwYWNrYWdlcy8qL3NyYy8qKi8qLnt0cyx0c3gsY3NzfVwiIiwKICAgICJ0ZXN0IjogIm5wbSBydW4gdGVzdCAtdyBAbWRzcy9jb3JlICYmIG5wbSBydW4gdGVzdCAtdyBAbWRzcy9hcHAiLAogICAgInRlc3Q6Y29yZSI6ICJucG0gcnVuIHRlc3QgLXcgQG1kc3MvY29yZSIsCiAgICAidGVzdDplMmUiOiAicGxheXdyaWdodCB0ZXN0IiwKICAgICJ0ZXN0OmUyZTp1aSI6ICJwbGF5d3JpZ2h0IHRlc3QgLS11aSIsCiAgICAidHlwZWNoZWNrIjogInRzYyAtcCBwYWNrYWdlcy9jb3JlL3RzY29uZmlnLmpzb24gLS1ub0VtaXQgJiYgdHNjIC1wIHBhY2thZ2VzL2FwcC90c2NvbmZpZy5qc29uIC0tbm9FbWl0IiwKICAgICJ2ZXJpZnkiOiAibnBtIHJ1biB0eXBlY2hlY2sgJiYgbnBtIHRlc3QgJiYgbnBtIHJ1biBsaW50ICYmIG5wbSBydW4gdGVzdDplMmUiCiAgfSwKICAiZGV2RGVwZW5kZW5jaWVzIjogewogICAgIkBlc2xpbnQvanMiOiAiXjEwLjAuMSIsCiAgICAiQHBsYXl3cmlnaHQvdGVzdCI6ICJeMS42MS4xIiwKICAgICJlc2xpbnQiOiAiXjEwLjcuMCIsCiAgICAiZXNsaW50LWNvbmZpZy1wcmV0dGllciI6ICJeMTAuMS44IiwKICAgICJlc2xpbnQtcGx1Z2luLXJlYWN0LWhvb2tzIjogIl43LjEuMSIsCiAgICAiZXNsaW50LXBsdWdpbi1yZWFjdC1yZWZyZXNoIjogIl4wLjUuMyIsCiAgICAiZ2xvYmFscyI6ICJeMTcuNy4wIiwKICAgICJwcmV0dGllciI6ICJeMy45LjUiLAogICAgInR5cGVzY3JpcHQiOiAiXjUuNS4zIiwKICAgICJ0eXBlc2NyaXB0LWVzbGludCI6ICJeOC42My4wIgogIH0KfQo='
write_b64 'tsconfig.json' 'ewogICJmaWxlcyI6IFtdLAogICJjb21tZW50IjogInR5cGVjaGVjayDjga/lkITjg5Hjg4PjgrHjg7zjgrjni6znq4vjgafooYzjgYbvvIhucG0gcnVuIHR5cGVjaGVja++8ieOAguOBk+OBruODleOCoeOCpOODq+OBr0lEReeUqOOBruODgOODn+ODvOOAgiIKfQo='
write_b64 'eslint.config.js' 'aW1wb3J0IGpzIGZyb20gJ0Blc2xpbnQvanMnOwppbXBvcnQgZ2xvYmFscyBmcm9tICdnbG9iYWxzJzsKaW1wb3J0IHJlYWN0SG9va3MgZnJvbSAnZXNsaW50LXBsdWdpbi1yZWFjdC1ob29rcyc7CmltcG9ydCByZWFjdFJlZnJlc2ggZnJvbSAnZXNsaW50LXBsdWdpbi1yZWFjdC1yZWZyZXNoJzsKaW1wb3J0IHRzZXNsaW50IGZyb20gJ3R5cGVzY3JpcHQtZXNsaW50JzsKaW1wb3J0IGVzbGludENvbmZpZ1ByZXR0aWVyIGZyb20gJ2VzbGludC1jb25maWctcHJldHRpZXInOwoKLy8gZXNsaW50LmNvbmZpZy5qc++8iG1vbm9yZXBvOiBwYWNrYWdlcy9jb3Jl44O7cGFja2FnZXMvYXBw77yJCmV4cG9ydCBkZWZhdWx0IHRzZXNsaW50LmNvbmZpZygKICB7IGlnbm9yZXM6IFsnKiovZGlzdCcsICdlMmUvKionLCAnKiovKi5jb25maWcuKiddIH0sCiAgewogICAgZXh0ZW5kczogW2pzLmNvbmZpZ3MucmVjb21tZW5kZWQsIC4uLnRzZXNsaW50LmNvbmZpZ3MucmVjb21tZW5kZWRUeXBlQ2hlY2tlZF0sCiAgICBmaWxlczogWydwYWNrYWdlcy8qL3NyYy8qKi8qLnt0cyx0c3h9J10sCiAgICBsYW5ndWFnZU9wdGlvbnM6IHsKICAgICAgZWNtYVZlcnNpb246IDIwMjIsCiAgICAgIGdsb2JhbHM6IGdsb2JhbHMuYnJvd3NlciwKICAgICAgcGFyc2VyT3B0aW9uczogewogICAgICAgIHByb2plY3RTZXJ2aWNlOiB0cnVlLAogICAgICAgIHRzY29uZmlnUm9vdERpcjogaW1wb3J0Lm1ldGEuZGlybmFtZSwKICAgICAgfSwKICAgIH0sCiAgICBwbHVnaW5zOiB7CiAgICAgICdyZWFjdC1ob29rcyc6IHJlYWN0SG9va3MsCiAgICAgICdyZWFjdC1yZWZyZXNoJzogcmVhY3RSZWZyZXNoLAogICAgfSwKICAgIHJ1bGVzOiB7CiAgICAgIC4uLnJlYWN0SG9va3MuY29uZmlncy5yZWNvbW1lbmRlZC5ydWxlcywKICAgICAgJ3JlYWN0LXJlZnJlc2gvb25seS1leHBvcnQtY29tcG9uZW50cyc6ICdvZmYnLAogICAgICAnQHR5cGVzY3JpcHQtZXNsaW50L25vLWV4cGxpY2l0LWFueSc6ICd3YXJuJywKICAgIH0sCiAgfSwKICBlc2xpbnRDb25maWdQcmV0dGllciwKKTsK'
write_b64 '.github/workflows/deploy.yml' 'bmFtZTogRGVwbG95IHRvIEdpdEh1YiBQYWdlcwoKb246CiAgcHVzaDoKICAgIGJyYW5jaGVzOiBbbWFpbl0KICB3b3JrZmxvd19kaXNwYXRjaDoKCnBlcm1pc3Npb25zOgogIGNvbnRlbnRzOiByZWFkCiAgcGFnZXM6IHdyaXRlCiAgaWQtdG9rZW46IHdyaXRlCgpjb25jdXJyZW5jeToKICBncm91cDogcGFnZXMKICBjYW5jZWwtaW4tcHJvZ3Jlc3M6IHRydWUKCmpvYnM6CiAgYnVpbGQ6CiAgICBydW5zLW9uOiB1YnVudHUtbGF0ZXN0CiAgICBzdGVwczoKICAgICAgLSB1c2VzOiBhY3Rpb25zL2NoZWNrb3V0QHY0CiAgICAgIC0gdXNlczogYWN0aW9ucy9zZXR1cC1ub2RlQHY0CiAgICAgICAgd2l0aDoKICAgICAgICAgIG5vZGUtdmVyc2lvbjogMjAKICAgICAgICAgIGNhY2hlOiBucG0KICAgICAgLSBydW46IG5wbSBjaQogICAgICAtIHJ1bjogbnBtIHRlc3QKICAgICAgLSBydW46IG5wbSBydW4gYnVpbGQKICAgICAgLSB1c2VzOiBhY3Rpb25zL3VwbG9hZC1wYWdlcy1hcnRpZmFjdEB2MwogICAgICAgIHdpdGg6CiAgICAgICAgICBwYXRoOiBwYWNrYWdlcy9hcHAvZGlzdAoKICBkZXBsb3k6CiAgICBuZWVkczogYnVpbGQKICAgIHJ1bnMtb246IHVidW50dS1sYXRlc3QKICAgIGVudmlyb25tZW50OgogICAgICBuYW1lOiBnaXRodWItcGFnZXMKICAgICAgdXJsOiAke3sgc3RlcHMuZGVwbG95bWVudC5vdXRwdXRzLnBhZ2VfdXJsIH19CiAgICBzdGVwczoKICAgICAgLSBpZDogZGVwbG95bWVudAogICAgICAgIHVzZXM6IGFjdGlvbnMvZGVwbG95LXBhZ2VzQHY0Cg=='
write_b64 '.gitignore' 'bm9kZV9tb2R1bGVzCmRpc3QKY292ZXJhZ2UKKi50c2J1aWxkaW5mbwouRFNfU3RvcmUKLmlkZWEKdGVzdC1yZXN1bHRzCnBsYXl3cmlnaHQtcmVwb3J0Cg=='

# ---------------------------------------------------------------------------
# 3.5. 生成ファイルをprettierで整形
#      （base64埋め込み/JSON生成に伴う軽微なフォーマット差異を吸収する）
# ---------------------------------------------------------------------------
npx prettier --write \
  packages/app/index.html \
  packages/app/tsconfig.json \
  packages/core/tsconfig.json \
  packages/core/src/geometry/chart.test.ts \
  packages/core/src/geometry/chart.ts \
  packages/core/src/index.ts \
  packages/app/src/components/charts/Charts.tsx \
  package.json tsconfig.json eslint.config.js \
  2>/dev/null || echo "[WARN] prettier整形をスキップしました（未インストールの可能性）"
echo "[OK] 生成ファイルをprettierで整形"

# node_modules を git 管理から外す（.gitignore 追加に伴う後始末。既に無ければ無害）
git rm -r --cached node_modules >/dev/null 2>&1 || true

# ---------------------------------------------------------------------------
# 4. 依存を再インストール（workspaces解決）
# ---------------------------------------------------------------------------
echo '--- npm install (workspaces) ---'
npm install --silent

# ---------------------------------------------------------------------------
# 5. 段階検証
# ---------------------------------------------------------------------------
echo '--- verify: import残存チェック ---'
if grep -rn "from '\(\./\|\(\.\./\)*\)parser/\(types\|slideMarkdown\|slideHeader\|deckLint\)'\|from '\(\./\|\(\.\./\)*\)schema/\(describe\|registry\)'" packages/app/src/ ; then
  echo '[ERROR] app内にcore参照の相対importが残っています'
  exit 1
fi
echo '[OK] app内にcore参照の相対importは残っていない'

echo '--- (1) core単体テスト（node env・DOM無し）---'
npm run test -w @mdss/core

echo '--- (2) app テスト ---'
npm run test -w @mdss/app

echo '--- (3) typecheck（core/app 独立）---'
npm run typecheck

echo '--- (4) lint（override無し・0 errors）---'
npx eslint packages/core/src packages/app/src

echo '--- (5) build（dist生成）---'
npm run build

echo '--- (6) dist/index.html の相対パス確認 ---'
if grep -q './assets/' packages/app/dist/index.html; then
  echo '[OK] base:'"'"'./'"'"' で相対パス出力を確認'
else
  echo '[WARN] dist/index.html の相対パスを目視確認してください'
fi

echo '=== apply-v0.3.3.sh completed ==='
